import { notFound } from 'next/navigation';
import { resolvePortalToken } from '@/lib/portal';
import { query } from '@/lib/db';
import { SignaturePad } from '@/components/SignaturePad';

export const dynamic='force-dynamic';

export default async function CustomerPortalPage({params}:{params:Promise<{token:string}>}){
 const {token}=await params; const access=await resolvePortalToken(token); if(!access) notFound();
 const [customer,quotes,orders,payments,fiscal]=await Promise.all([
  query<any>(`SELECT name,email,phone FROM customers WHERE id=$1 AND organization_id=$2`,[access.customer_id,access.organization_id]),
  query<any>(`SELECT number,status,total,valid_until,created_at FROM quotes WHERE organization_id=$1 AND customer_id=$2 ORDER BY created_at DESC LIMIT 20`,[access.organization_id,access.customer_id]),
  query<any>(`SELECT w.id,w.number,w.status,w.title,w.description,w.scheduled_start,w.completed_at,w.amount,EXISTS(SELECT 1 FROM work_order_signatures s WHERE s.work_order_id=w.id) signed FROM work_orders w WHERE w.organization_id=$1 AND w.customer_id=$2 ORDER BY w.created_at DESC LIMIT 30`,[access.organization_id,access.customer_id]),
  query<any>(`SELECT id,status,amount,due_at,paid_at,payment_url,method FROM payments WHERE organization_id=$1 AND customer_id=$2 ORDER BY created_at DESC LIMIT 30`,[access.organization_id,access.customer_id]),
  query<any>(`SELECT status,number,verification_code,amount,pdf_url,xml_url,issued_at FROM fiscal_documents WHERE organization_id=$1 AND customer_id=$2 ORDER BY created_at DESC LIMIT 20`,[access.organization_id,access.customer_id])
 ]);
 const c=customer.rows[0]; const signable=orders.rows.find((o:any)=>['IN_PROGRESS','COMPLETED'].includes(o.status)&&!o.signed);
 return <main className="portal-shell"><header className="portal-head"><div className="brand">Serviço<span>OS</span></div><div><strong>{access.organization_name}</strong><p>Portal seguro do cliente</p></div></header><section className="portal-hero"><span className="eyebrow">Área do cliente</span><h1>Olá, {c?.name || access.customer_name}.</h1><p>Acompanhe serviços, cobranças, documentos e aceite de execução.</p></section><div className="portal-grid"><section className="card"><h2>Ordens de serviço</h2>{orders.rows.length?orders.rows.map((o:any)=><div className="portal-row" key={o.id}><div><strong>OS #{o.number} — {o.title}</strong><p>{o.description||'Sem observações'}</p></div><div><span className="badge blue">{o.status}</span>{o.signed&&<span className="badge green">ASSINADA</span>}</div></div>):<div className="empty">Nenhuma OS.</div>}</section><section className="card"><h2>Pagamentos</h2>{payments.rows.length?payments.rows.map((p:any)=><div className="portal-row" key={p.id}><div><strong>{Number(p.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><p>{p.paid_at?'Pago':'Vencimento '+(p.due_at?new Date(p.due_at).toLocaleDateString('pt-BR'):'a definir')}</p></div><div><span className={`badge ${p.status==='PAID'?'green':'amber'}`}>{p.status}</span>{p.payment_url&&p.status!=='PAID'&&<a className="btn small" href={p.payment_url}>Pagar</a>}</div></div>):<div className="empty">Nenhuma cobrança.</div>}</section><section className="card"><h2>Orçamentos</h2>{quotes.rows.length?quotes.rows.map((q:any)=><div className="portal-row" key={q.number}><div><strong>Orçamento #{q.number}</strong><p>{Number(q.total).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p></div><span className="badge">{q.status}</span></div>):<div className="empty">Nenhum orçamento.</div>}</section><section className="card"><h2>Notas e documentos fiscais</h2>{fiscal.rows.length?fiscal.rows.map((f:any,i:number)=><div className="portal-row" key={`${f.number}-${i}`}><div><strong>{f.number?`NFS-e ${f.number}`:'Documento em processamento'}</strong><p>{Number(f.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</p></div><div><span className="badge">{f.status}</span>{f.pdf_url&&<a className="btn small secondary" href={f.pdf_url}>PDF</a>}</div></div>):<div className="empty">Nenhum documento fiscal.</div>}</section></div>{signable&&<section className="card portal-sign"><h2>Assinatura da OS #{signable.number}</h2><p>Use o campo abaixo para confirmar a execução do serviço.</p><SignaturePad token={token} workOrderId={signable.id}/></section>}<footer className="portal-footer">Acesso protegido por token temporário. Não compartilhe este link publicamente.</footer></main>
}
