import { getCurrentSession } from '@/lib/auth';
import { query } from '@/lib/db';

export default async function AgendaPage(){
  const session=(await getCurrentSession())!;
  const [appointments,customers,users,orders]=await Promise.all([
    query<any>(`SELECT a.*,c.name customer_name,u.name assigned_name,w.number work_order_number FROM appointments a JOIN customers c ON c.id=a.customer_id LEFT JOIN users u ON u.id=a.assigned_to LEFT JOIN work_orders w ON w.id=a.work_order_id WHERE a.organization_id=$1 AND a.starts_at>=now()-interval '7 days' ORDER BY a.starts_at ASC LIMIT 200`,[session.organization_id]),
    query<any>(`SELECT id,name FROM customers WHERE organization_id=$1 AND status='ACTIVE' ORDER BY name LIMIT 300`,[session.organization_id]),
    query<any>(`SELECT u.id,u.name FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.organization_id=$1 AND m.is_active=true ORDER BY u.name`,[session.organization_id]),
    query<any>(`SELECT id,number,title,customer_id FROM work_orders WHERE organization_id=$1 AND status NOT IN ('COMPLETED','CANCELLED') ORDER BY created_at DESC LIMIT 200`,[session.organization_id])
  ]);
  return <><div className="page-head"><div><h1>Agenda</h1><p>Atendimentos, técnicos e ordens de serviço em uma única visão.</p></div></div><div className="grid-2"><section className="card"><h2>Novo agendamento</h2><form method="post" action="/api/appointments"><div className="field"><label>Título</label><input className="input" name="title" required placeholder="Instalação / visita técnica"/></div><div className="field"><label>Cliente</label><select className="select" name="customer_id" required><option value="">Selecione</option>{customers.rows.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="field"><label>OS (opcional)</label><select className="select" name="work_order_id"><option value="">Sem OS</option>{orders.rows.map((o:any)=><option key={o.id} value={o.id}>#{o.number} — {o.title}</option>)}</select></div><div className="field"><label>Técnico</label><select className="select" name="assigned_to"><option value="">Sem responsável</option>{users.rows.map((u:any)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div><div className="field"><label>Início</label><input className="input" type="datetime-local" name="starts_at" required/></div><div className="field"><label>Fim</label><input className="input" type="datetime-local" name="ends_at" required/></div><div className="field"><label>Local</label><input className="input" name="location"/></div><div className="form-actions"><button className="btn">Agendar</button></div></form></section><section className="card"><h2>Próximos atendimentos</h2><div className="timeline">{appointments.rows.length?appointments.rows.map((a:any)=><div className="timeline-item" key={a.id}><div><strong>{new Date(a.starts_at).toLocaleString('pt-BR',{timeZone:session.organization_name?undefined:undefined})}</strong><span className="badge blue">{a.status}</span></div><h3>{a.title}</h3><p>{a.customer_name}{a.work_order_number?` · OS #${a.work_order_number}`:''}{a.assigned_name?` · ${a.assigned_name}`:''}</p>{a.location&&<small>{a.location}</small>}</div>):<div className="empty">Nenhum atendimento agendado.</div>}</div></section></div></>
}
