import { getCurrentSession } from '@/lib/auth';
import { query } from '@/lib/db';

export default async function ChecklistsPage(){
 const session=(await getCurrentSession())!;
 const [templates,orders,recentItems]=await Promise.all([
  query<any>(`SELECT t.id,t.name,t.description,count(i.id)::int item_count FROM checklist_templates t LEFT JOIN checklist_template_items i ON i.template_id=t.id WHERE t.organization_id=$1 AND t.active=true GROUP BY t.id ORDER BY t.created_at DESC`,[session.organization_id]),
  query<any>(`SELECT id,number,title FROM work_orders WHERE organization_id=$1 AND status NOT IN ('CANCELLED') ORDER BY created_at DESC LIMIT 200`,[session.organization_id]),
  query<any>(`SELECT i.id,i.label,i.is_completed,i.response_text,w.number work_order_number FROM work_order_checklist_items i JOIN work_orders w ON w.id=i.work_order_id WHERE i.organization_id=$1 ORDER BY w.created_at DESC,i.sort_order LIMIT 120`,[session.organization_id])
 ]);
 return <><div className="page-head"><div><h1>Checklists técnicos</h1><p>Padronize execução, evidências e aceite operacional.</p></div></div><div className="grid-3"><section className="card"><h2>Novo template</h2><form method="post" action="/api/checklists"><input type="hidden" name="action" value="create_template"/><div className="field"><label>Nome</label><input className="input" name="name" required placeholder="Instalação padrão"/></div><div className="field"><label>Itens — um por linha</label><textarea className="textarea" name="items" required placeholder={'Conferir alimentação elétrica\nRegistrar número de série\nTestar funcionamento'}/></div><div className="form-actions"><button className="btn">Criar template</button></div></form></section><section className="card"><h2>Aplicar em uma OS</h2><form method="post" action="/api/checklists"><input type="hidden" name="action" value="apply_template"/><div className="field"><label>Template</label><select className="select" name="template_id" required><option value="">Selecione</option>{templates.rows.map((t:any)=><option key={t.id} value={t.id}>{t.name} ({t.item_count})</option>)}</select></div><div className="field"><label>Ordem de serviço</label><select className="select" name="work_order_id" required><option value="">Selecione</option>{orders.rows.map((o:any)=><option key={o.id} value={o.id}>#{o.number} — {o.title}</option>)}</select></div><div className="form-actions"><button className="btn">Aplicar checklist</button></div></form><div className="template-list">{templates.rows.map((t:any)=><div key={t.id} className="template-row"><strong>{t.name}</strong><span>{t.item_count} itens</span></div>)}</div></section><section className="card"><h2>Execução recente</h2><div className="check-list">{recentItems.rows.length?recentItems.rows.map((i:any)=><form method="post" action="/api/checklists" key={i.id} className="check-row"><input type="hidden" name="action" value="update_item"/><input type="hidden" name="item_id" value={i.id}/><label><input type="checkbox" name="is_completed" defaultChecked={i.is_completed}/> <strong>OS #{i.work_order_number}</strong> — {i.label}</label><input className="input" name="response_text" defaultValue={i.response_text||''} placeholder="Observação"/><button className="btn secondary">Salvar</button></form>):<div className="empty">Nenhum checklist aplicado.</div>}</div></section></div></>
}
