import { getCurrentSession } from '@/lib/auth';
import { query } from '@/lib/db';
import { nfseReadiness } from '@/lib/nfse';

function Status({ok,label}:{ok:boolean;label:string}){return <div className="integration-row"><div><strong>{label}</strong><p>{ok?'Configuração disponível no ambiente.':'Aguardando credenciais/configuração.'}</p></div><span className={`badge ${ok?'green':'amber'}`}>{ok?'PRONTO':'PENDENTE'}</span></div>}

export default async function IntegracoesPage(){
 const session=(await getCurrentSession())!; const nfse=nfseReadiness();
 const rows=await query<any>(`SELECT kind,provider,status,updated_at FROM integrations WHERE organization_id=$1 ORDER BY kind,provider`,[session.organization_id]);
 const billing=await query<any>(`SELECT plan,billing_status,stripe_customer_id FROM organizations WHERE id=$1`,[session.organization_id]);
 const org=billing.rows[0];
 return <><div className="page-head"><div><h1>Integrações</h1><p>Estado operacional das conexões externas e da infraestrutura.</p></div></div><div className="grid-2"><section className="card"><h2>Infraestrutura</h2><Status ok={true} label="PostgreSQL Neon — produção"/><Status ok={true} label="Storage privado PostgreSQL"/><Status ok={Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM)} label="E-mail transacional — Resend"/><Status ok={Boolean(process.env.WHATSAPP_ACCESS_TOKEN&&process.env.WHATSAPP_PHONE_NUMBER_ID)} label="WhatsApp Cloud API"/><Status ok={Boolean(process.env.STRIPE_SECRET_KEY&&process.env.STRIPE_WEBHOOK_SECRET)} label="Stripe + webhooks"/><Status ok={nfse.certificateConfigured} label={`NFS-e Nacional — ${nfse.environment}`}/><p className="muted" style={{fontSize:12}}>Segredos são carregados pelo ambiente do servidor e não aparecem nesta tela.</p></section><section className="card"><h2>Assinatura ServiçoOS</h2><p>Plano atual: <strong>{org?.plan}</strong></p><p>Status: <span className="badge blue">{org?.billing_status}</span></p><div className="plan-actions"><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value="STARTER"/><button className="btn secondary">Starter</button></form><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value="PRO"/><button className="btn">Pro</button></form><form method="post" action="/api/billing/checkout"><input type="hidden" name="plan" value="BUSINESS"/><button className="btn secondary">Business</button></form></div><hr className="sep"/><h2>Conectores cadastrados</h2>{rows.rows.length?rows.rows.map((r:any)=><div className="integration-row" key={`${r.kind}-${r.provider}`}><div><strong>{r.kind}</strong><p>{r.provider}</p></div><span className="badge green">{r.status}</span></div>):<div className="empty">Nenhum conector específico por empresa cadastrado.</div>}</section></div></>
}
